### ISSUE TITLE
Unresponsiveness on infinite loop in function

### ISSUE THREAD

**Issue by xDeadpoolx** [JCluzet/42_EXAM#13]
I happened to made a mistake that made the exam freeze after asking for grading.
I had to do ft_strlen. Here<s my initial answer. Note the while loop. "str" is missing [x].
Giving that answer and asking for grading put the program into an infinite loop.
Had to kill the program and relaunch the exam.

Still on Ubuntu in WSL2 on Win11.

`#include <unistd.h>

int	ft_strlen(char *str)
{
	int	x;

	x = 0;
	while (str)
		x++;
	return (x);
}`

**Comment by JCluzet** [comment]
I know this problem.
This one is present since the beginning and at that time I had not found a way to solve it.
I'm going to work to try to solve this problem. 

If this problem is fixed in a next version I will let you know directly.

**Comment by xDeadpoolx** [comment]
No problem. Maybe mark it as a known issue.
Would forcing a timeout message be a solution to break the loop if there is
no grading answer after 3min ?

Cheers.

**Comment by JCluzet** [comment]
Today is a great day! 
I just found out how to detect a while loop in a program. 

Your idea was the one I had, but to implement it was rather complicated, because if I launch a bash program that tests your exercise I had to wait for it to finish to perform another action (and it never happened because of the infinite loop...)

However since the auto-correction of examrank06 I learned to manage PIDs and so I now run another thread at the same time that will check this. 

Thanks again for the idea, let me know if it works well.

Have a good exam!
