### ISSUE TITLE
Exam Rank 05 nullptr error

### ISSUE THREAD

**Issue by AslanAmca** [JCluzet/42_EXAM#172]
Functions that take parameters, such as ASpell *, need to check for nullptr. If nullptr is used, it will fail and give an error like “error: use of undeclared identifier ‘nullptr’”. Normally there should be no problem using nullptr.

cpp_module01/Warlock.cpp:27:16: error: use of undeclared identifier 'nullptr'
   27 |     if (spell != nullptr)
      |                ^
1 error generated.

<--------------~-~-~-~-~-~-~-~-~------------>
Richard: This looks like another boring day.$
Richard: I am Richard, the Titled!$
Target Practice Dummy has been fwooshed!$
Richard: My job here is done!$
\n
<--------------~-~-~-~-~-~-~-~-~------------>\n\n
<--------------~-~-~-~-~-~-~-~-~------------>
\n
<--------------~-~-~-~-~-~-~-~-~------------>

**Comment by JCluzet** [comment]
Hey @AslanAmca,
First, thank you for using Grademe.

The reason you're encountering the error "**use of undeclared identifier 'nullptr'**" is because `_nullptr_` was introduced in C++11, and it's not available in C++98, which Grademe is currently using for compatibility. To ensure Grademe Exam works on as many computers as possible, we are using C++98. Therefore, `_nullptr_` does not exist in this context yet.

However, you can replace `_nullptr_` with `**NULL**`, which will achieve the same effect. Here's an example of how you can modify your code:


```
void Warlock(ASpell* spell) {
    if (spell != nullptr) {
       // ...
    }
}
```


Modified for C++98:

```
void Warlock(ASpell* spell) {
    if (spell != NULL) {
        // ...
    }
}
```


This change should resolve the error and allow your code to compile and grademe correctly under the C++98 standard.

Happy Coding!

Jo
