### ISSUE TITLE
Subject folder get deleted while doing exam practice

### ISSUE THREAD

**Issue by dom-dorium** [JCluzet/42_EXAM#19]
Happened to me while I was doing a practice exam rank 02 on the 2nd question the subject folder with the subject got deleted.

**Comment by JCluzet** [comment]
Hi,

The subject file is deleted with each successful exercise, this is normal.
It is immediately replaced by the next subject of the new exercise. 
You didn't get a new subject folder? 
If you don't have any subject, please tell me the exercise and the level you were on. 
Thanks again!

**Comment by Kolterdyx** [comment]
I also had this problem, while doing the student exam 03. After finishing the first excercise (inter), The `subjects` folder got deleted, and a new one called `success` was created. I didn't get the subject for the next excercise (`ft_prinf`), but I was able to "cheat" and get it through a folder I found in the exam called `.subjects/STUD_PART/exam_03/1`

**Comment by dom-dorium** [comment]
On my part the first question of exam rank 02 always give you a subject folder with the subject but since a few days it delete the folder on the question 2 also I've noticed that a lot of question tell me to force successs them I don't know if it's a bug or a features for missings test but that's all the bug I could find. And beyond that what you have coded is fantastic !

**Comment by JCluzet** [comment]
Thank you very much, in fact the program indicated that it did not have a correction because a correction folder was not created correctly since my last push.
After the success of an exercise, it could not create what was needed for the next one, neither the subjects folder, nor the grading folder (folder that internally allows the correction of the exercise)
And as a result it indicated that there was no correction possible.

**I just fixed it now.**
Let me know if there is a new problem.
Sorry again for the inconvenience.
