### ISSUE TITLE
Input command space issue

### ISSUE THREAD

**Issue by arikhativa** [JCluzet/42_EXAM#26]
when trying to use a cmd (e.g. "help") if there is space at the end ("help ") there is an invalid input error:

![image](https://user-images.githubusercontent.com/49197152/204132854-a8c823c7-6644-4078-a4dd-5986c3ebac35.png)

solution:
main.cpp:
line 17:
```
input = line;
input.erase(remove_if(input.begin(), input.end(), isspace), input.end());
```

this will cut the input string at the first space.

**Comment by arikhativa** [comment]
btw do you need any help with this project? i would love to contribute :)

**Comment by JCluzet** [comment]
Hi arikhativa 👋

Thanks for your proposal, I just modified the main.cpp file in order to take care of useless spaces at the beginning or end of the command.

If you want to contribute to the project it's with great pleasure, you are free to add by yourself the things you find interesting, and propose a pull request, I will gladly accept the improvements you bring to 42_EXAM

**Comment by arikhativa** [comment]
can you add me as a contributer?

**Comment by JCluzet** [comment]
Hi,

You will be automatically added as a contributor by submitting a pull request :) 
For that you can follow this very simple tuto :
[Become a contributor](https://www.youtube.com/watch?v=rgbCcBNZcdQ)

Once your pull request proposed, I will accept it quickly and you will automatically become a contributor of the project.

If you have any question don't hesitate, thanks again for your help
