### ISSUE TITLE
Error after level 1 on Exam rank 02 of student level

### ISSUE THREAD

**Issue by ylu211** [JCluzet/42_EXAM#3]
After first_word and rot_13 (the two I've tried), the program crash with this message error :

a.out(3427,0x10f594e00) malloc: *** error for object 0x7fff20616738: pointer being freed was not allocated
a.out(3427,0x10f594e00) malloc: *** set a breakpoint in malloc_error_break to debug
/bin/sh: line 1:  3427 Abort trap: 6           ./a.out
make: *** [all] Error 134

**Comment by JCluzet** [comment]
Hello @ylu211 and thank you very much for your feedback, so that I can investigate this problem and solve it as soon as possible, could you answer these questions:

- What is your OS ?
- Were you at 42 at the time of the crash?
- Did you have time to see the "waiting..." before the crash? 
- Do you have the files of the first_word or rot_13 ?(so I can redo the bug on my side)
Thank you for your help!

**Comment by ylu211** [comment]
Hello @JCluzet sorry I really haven't been specific enough.. 
I used MacOS and I wasn't at 42 at the time of the crash. I don't have the file of these two but I just retry the test and I had the same error with a ft_putstr :
`#include <unistd.h>

void	ft_putstr(char *str){
	int i =0;
	while(str[i]){
		write(1,&str[i],1);
		i++;
	}
}`
It happened right after the first level, the program showed 'Success', then gave me the subject of level 2, and it crashed.
<img width="499" alt="Capture d’écran 2022-06-06 à 10 09 35" src="https://user-images.githubusercontent.com/96550110/172121731-f9f7ca83-277b-4008-b383-27c9827dcbac.png">

**Comment by JCluzet** [comment]
Thank you very much for your answer and the details about this problem.

I just found an explanation in my code that could create this crash 
However, to be sure of the update I will do, could you give me the complete path of your 42_EXAM file at the time of the exam?

As you could see the problem comes from a string (concerning your path) which is not correctly initialized in my program. 

We can notice it with the "Assignment: H?1?'H?/rendu/" on your screenshot. 

Thanks again!

**Comment by JCluzet** [comment]
I just pushed a new version that fixes this problem. 
Let me know if it works :)
