### ISSUE TITLE
Exam Rank 02 - Lvl 3 - rev_wstr

### ISSUE THREAD

**Issue by gwolf-011235** [JCluzet/42_EXAM#30]
The subject states: "there won't be any "additional" spaces (meaning that there won't be additionnal spaces at the beginning or at 
the end of the string, and words will always be separated by exactly one space)"

The testing input doesn't seem to follow this => "./a.out   done! well it, did You  "
The input shouldn't have any white space at the beginning or at the end.

Also it seems to expect a "wrong" output => "You did it, well done! $" 
I don't think there should be a space at the end.

Additionally the test does only seem to check for spaces and not for any tabs.

[subject](https://github.com/JCluzet/42_EXAM/blob/main/.subjects/STUD_PART/exam_02/3/rev_wstr/attachement/subject.en.txt)

**Comment by JCluzet** [comment]
Hi gwolf-011235 👋

First of all, thank you for using 42_EXAM.
This exercise is currently in **BETA** because it was not created by me but by a [contribution](https://github.com/JCluzet/42_EXAM/blob/main/CONTRIBUTING.md) from @pandaero 📖
I will wait to see if he can answer you directly to check this by himself.
Otherwise I will come back to you quickly to check and solve it by myself.

- `rev_wstr` successRate per login : _**37,35 %**_

Thanks again for your issue.

**Comment by anfreire** [comment]
Hello, I'm not sure if there is an issue, but everything appears to function ok when I compile with "| cat -e" after the command on bash and shell. But the program keeps failing me :´(

I created this ticket because the trace contains a blank space at the conclusion; could you kindly check it?

If I made a mistake, I apologize in advance, and I appreciate you so much for this initiative. 
[rev_wstr.zip](https://github.com/JCluzet/42_EXAM/files/10186058/rev_wstr.zip)

**Comment by JCluzet** [comment]
Hi @gwolf-011235 & @anfreire 👋

I'm coming back to you because we haven't had any response from @pandaero..
So I went ahead and looked into the problem.

Indeed the subject says never test anything tricky and there was a test including two spaces at the end and the beginning.
This test has now been removed and replaced by better ones.

@anfreire, concerning your code, I confirm that it is now `SUCCESS`.
If you have any other problems, please do not hesitate to open a new one.

Good luck with your exams!
