### ISSUE TITLE
[Exam02] Small error on lvl03 sort_list exercise correction

### ISSUE THREAD

**Issue by Kuninoto** [JCluzet/42_EXAM#39]
Hello there!,
Before anything let me take the opportunity to congratulate you guys for this amazing project.
I'm here to report a little "bug" - if that's even the correct name for this little thing :sweat_smile: - that happens on exercise "sort_list" of level 03
Its subject goes:
```
You must use the type t_list described in the file list.h 
that is provided to you. You must include that file 
(#include "list.h"), but you must not turn it in. We will use our own 
to compile your assignment.
```
But when I submitted without the list.h in my submission folder, I've got a fail and the following trace: 
```
----------------8<-------------[ START TEST 
        💻 TEST
./a.out         🔎 YOUR OUTPUT:
../../rendu/sort_list/sort_list.c:1:10: fatal error: list.h: No such file or directory
    1 | #include "list.h"
      |          ^~~~~~~~
compilation terminated.

        ❌ COMPILATION ERROR
----------------8<------------- END TEST ]

```
This error is obviously not _wrong_ nor _alienated_ (in the sense that in fact list.h is missing in my submission) but is not in accordance to the subject. Therefore I found it better to report.
I've also took the liberty to check the source code and from what I understood `auto_correc_main.sh` compiles the submission folder on its own, i.e no interaction with the grading section/folder, and that's why. The script tries to compile my source code based only on my submission folder, doesn't find list.h and fails.

**Comment by JCluzet** [comment]
Hi @Kuninoto 👋

First of all, thank you for using **42_EXAM**.
Thank you for your issue which is very well explained.
The exercise you mention is currently in BETA because it is a [contribution](https://github.com/JCluzet/42_EXAM/blob/main/CONTRIBUTING.md) of @pandaero 

However, I took the time to check and indeed the list.h file is necessary, contrary to the subject.
So I modified the tester.sh file to copy the list.h file at the time of the correction.

This is now fixed.
Thanks again, and if you have any new problem don't hesitate to reopen an Issue :)
