### ISSUE TITLE
Missing subject in union exercise

### ISSUE THREAD

**Issue by waltergcc** [JCluzet/42_EXAM#81]
Hello,
passing by to let you know that the subject is missing in folder .subjects/STUD_PART/exam_02/1/union/
Thank you so much for the amazing work with this program.

**Comment by JCluzet** [comment]
Hi @waltergcc 👋🏼
If you don't have the union subject it's because the topic UNION was deleted from 42 at exam 03. 

So it has been deleted from 42_EXAM. 

However if you have an old version of 42_EXAM you may not have the subject anymore. 
Just delete the 42_EXAM folder and re-clone it. 
This will solve the problem.
