### ISSUE TITLE
Exam02 level 1 search_and_replace. Union subject is missing too.

### ISSUE THREAD

**Issue by Suigetsu** [JCluzet/42_EXAM#83]
Hello, i hope you're doing well. 
I've encountered a problem with the search_and_replace exercise.

The output of this example in the subject `**"zaz" "art" "zul" | cat -e is zaz$**` but the trace says otherwise:

----------------8<-------------[ START TEST
        💻 TEST
./a.out "zaz" "art" "zul"
        🔎 YOUR OUTPUT:
zaz$
        🗝 EXPECTED OUTPUT:
$
----------------8<------------- END TEST ]

**Comment by JCluzet** [comment]
Hi @Suigetsu 

The problem of `search_and_replace` is now solved with pr #82 , however for the problem of Union it is normal because it has been removed from 42, and therefore from 42_EXAM. 
I would find a solution to instantly update the repo, but at the moment you can just delete the 42_EXAM folder and clone it again.
